export type ScanMode = "premarket" | "gap-and-go" | "extended" | "all";
export type EventRule = "opening" | "extended";
export type Direction = "up" | "down" | "both";
export type Side = Exclude<Direction, "both">;
export type Bar = {
  t: string;
  o: number;
  h: number;
  l: number;
  c: number;
  v: number;
};
export type Session = { date: string; open: string; close: string };
export type StockSnapshot = {
  latestTrade?: { t: string; p: number } | null;
  dailyBar?: Bar | null;
  prevDailyBar?: Bar | null;
};
export type SessionQuote = {
  sessionDate: string;
  price: number | null;
  priceTime: string | null;
  previousClose: number | null;
  open: number | null;
  priceChange: number | null;
  openingGap: number | null;
  changeFromOpen: number | null;
  volume: number | null;
  fetchedAt: string;
};
export type Asset = {
  symbol: string;
  name: string;
  exchange: string;
  status: string;
  tradable: boolean;
  class: string;
};
export type Trigger = {
  time: string;
  observedPrice: number;
  thresholdPrice: number;
  side: Side;
  precision: "1Min";
  exactTradePrice: null;
};
export type Provenance = {
  provider: "Alpaca";
  feed: "iex" | "sip";
  adjustment: "split";
  timeframe: "1Min" | "snapshot";
  fetchedAt: string;
  asOf: string;
  delayMinutes: number;
  coverage: string;
  calendar: "Alpaca";
  reference: string;
  version: string;
};
export type Outcomes = {
  continuedFromOpen: boolean | null;
  open: number | null;
  high: number | null;
  low: number | null;
  close: number | null;
  openReturn: number | null;
  return5m: number | null;
  return15m: number | null;
  return30m: number | null;
  return60m: number | null;
  openToHigh: number | null;
  openToLow: number | null;
  openToClose: number | null;
  previousCloseToClose: number | null;
  mfe: number | null;
  mae: number | null;
  gapHeld: boolean | null;
  gapFilled: boolean | null;
  gapFillTime: string | null;
  failedGap: boolean | null;
  continued: boolean | null;
  exceededExtendedHigh: boolean | null;
  followThrough2pct: boolean | null;
  closedAbovePrevious: boolean | null;
  regularBars: number;
  expectedRegularBars: number;
  completeRegular: boolean;
};
export type GapEvent = Outcomes & {
  id: string;
  symbol: string;
  date: string;
  previousClose: number;
  previousCloseTime: string;
  threshold: number;
  side: Side;
  ambiguousDirection: boolean;
  triggers: Trigger[];
  firstTrigger: Trigger;
  maxGap: number | null;
  maxGapTime: string | null;
  extendedHigh: number | null;
  extendedLow: number | null;
  extendedVolume: number | null;
  sessionVolume: number | null;
  extendedBars: number;
  warnings: string[];
};
export type ScannerRow = {
  premarketChange?: number | null;
  premarketVolume?: number | null;
  premarketPrice?: number | null;
  premarketTime?: string | null;
  premarketSessionDate?: string;
  symbol: string;
  name: string;
  exchange: string;
  assetType: string;
  price: number | null;
  previousClose: number | null;
  gap: number | null;
  high: number | null;
  low: number | null;
  volume: number | null;
  previousVolume: number | null;
  relativeVolume: number | null;
  dollarVolume: number | null;
  marketCap: number | null;
  marketCapInfo?: {
    source: "Nasdaq";
    fetchedAt: string;
    sourceAsOf: string | null;
  };
  maxGapTime: string | null;
  latestTime: string | null;
  extendedBars: Bar[];
  referenceTime: string | null;
  quote: SessionQuote | null;
};
export type Summary = {
  events: number;
  metrics: Record<string, { value: number | null; n: number }>;
  best: { date: string; value: number } | null;
  worst: { date: string; value: number } | null;
};
export type BacktestResult = {
  rule?: EventRule;
  symbol: string;
  start: string;
  end: string;
  events: GapEvent[];
  summary: Summary;
  examined: number;
  insufficient: { date: string; reason: string }[];
  provenance: Provenance;
  warnings: string[];
};
export type EventChartResult = {
  symbol: string;
  session: Session;
  previous: Session;
  previousClose: number | null;
  bars: Bar[];
  provenance: Provenance;
  warnings: string[];
};
export type ScanContext = {
  assets: Asset[];
  previous: Session;
  session: Session;
  asOf: string;
  provenance: Provenance;
  historyStart: string;
  quoteSession: Session;
  quotePrevious: Session;
  warnings: string[];
};
export type ScanBatch = {
  mode?: ScanMode;
  rows: ScannerRow[];
  unavailable: { symbol: string; reason: string }[];
  provenance: Provenance;
  warnings: string[];
};
